### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by flosse** [hgzimmerman/rocket-file-cache#13]
Would you mind to add a `CHANGELOG.md` to the repo?

**Comment by hgzimmerman** [comment]
I should, I'm version bumping a tad too aggressively and I imagine that makes keeping up to date difficult. I'll get one included tomorrow.

**Comment by hgzimmerman** [comment]
I have a first draft of the changelog up [here](https://github.com/hgzimmerman/rocket-file-cache/blob/master/CHANGELOG.md).

I'll leave this Issue open for a few days while I touch it up and record changes from earlier versions.

**Comment by flosse** [comment]
great 👍

**Comment by hgzimmerman** [comment]
I feel like the changelog is in a decent state.
Closing this issue now.
